In [1]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [8]:
voc_size=10000

In [9]:
onehot_repr=[one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[3681, 7398, 2508, 4525], [3681, 7398, 2508, 4788], [3681, 9062, 2508, 2839], [1176, 7309, 6222, 3038, 1013], [1176, 7309, 6222, 3038, 9826], [5556, 3681, 7000, 2508, 5960], [7104, 7304, 5349, 3038]]


In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [14]:
#pre padding - 0's added in front
#post padding - 0's added at end
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3681 7398 2508 4525]
 [   0    0    0    0 3681 7398 2508 4788]
 [   0    0    0    0 3681 9062 2508 2839]
 [   0    0    0 1176 7309 6222 3038 1013]
 [   0    0    0 1176 7309 6222 3038 9826]
 [   0    0    0 5556 3681 7000 2508 5960]
 [   0    0    0    0 7104 7304 5349 3038]]


In [15]:
dim=10

In [16]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 112ms/step


array([[-0.0038746 , -0.02084923, -0.02584668, -0.03477551,  0.00577565,
        -0.03066472, -0.03972143, -0.02665726, -0.02820963, -0.01614851],
       [-0.0038746 , -0.02084923, -0.02584668, -0.03477551,  0.00577565,
        -0.03066472, -0.03972143, -0.02665726, -0.02820963, -0.01614851],
       [-0.0038746 , -0.02084923, -0.02584668, -0.03477551,  0.00577565,
        -0.03066472, -0.03972143, -0.02665726, -0.02820963, -0.01614851],
       [-0.0038746 , -0.02084923, -0.02584668, -0.03477551,  0.00577565,
        -0.03066472, -0.03972143, -0.02665726, -0.02820963, -0.01614851],
       [-0.01494991, -0.00822548, -0.04439615, -0.00042254,  0.00816603,
        -0.03336284, -0.02000228, -0.03591912, -0.01407262,  0.02728641],
       [ 0.02875957, -0.04568407,  0.02525654, -0.01161611,  0.03278137,
         0.02274079, -0.02348976,  0.03729954,  0.03198022,  0.04164978],
       [ 0.03889925,  0.04635472, -0.0241456 , -0.0207526 , -0.01989474,
        -0.00173058,  0.01357058,  0.0043465 

In [21]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 21ms/step
[[[-0.0038746  -0.02084923 -0.02584668 -0.03477551  0.00577565
   -0.03066472 -0.03972143 -0.02665726 -0.02820963 -0.01614851]
  [-0.0038746  -0.02084923 -0.02584668 -0.03477551  0.00577565
   -0.03066472 -0.03972143 -0.02665726 -0.02820963 -0.01614851]
  [-0.0038746  -0.02084923 -0.02584668 -0.03477551  0.00577565
   -0.03066472 -0.03972143 -0.02665726 -0.02820963 -0.01614851]
  [-0.0038746  -0.02084923 -0.02584668 -0.03477551  0.00577565
   -0.03066472 -0.03972143 -0.02665726 -0.02820963 -0.01614851]
  [-0.01494991 -0.00822548 -0.04439615 -0.00042254  0.00816603
   -0.03336284 -0.02000228 -0.03591912 -0.01407262  0.02728641]
  [ 0.02875957 -0.04568407  0.02525654 -0.01161611  0.03278137
    0.02274079 -0.02348976  0.03729954  0.03198022  0.04164978]
  [ 0.03889925  0.04635472 -0.0241456  -0.0207526  -0.01989474
   -0.00173058  0.01357058  0.0043465  -0.03722998  0.02277097]
  [-0.0229135   0.00648876  0.01958443  0.01694962 -0.03424